# Generated by Django 4.1.5 on 2023-01-22 13:35

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('hostel', models.CharField(choices=[('SE', 'Satluj East'), ('SW', 'Satluj West'), ('BE', 'Beas East'), ('BW', 'Beas West'), ('CE', 'Chenab East'), ('CW', 'Chenab West'), ('RE', 'Raavi East'), ('RW', 'Raavi West')], max_length=100)),
                ('room', models.CharField(default='NA', max_length=10)),
                ('degree', models.CharField(choices=[('BTECH', 'Becholer of Technology'), ('MTECH', 'Master of Technology'), ('PHD', 'PHD'), ('MSC', 'Master of Science')], max_length=100)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('mess', models.CharField(choices=[('Kanaka', 'Kanaka Mess'), ('Bhopal', 'Bhopal Mess')], max_length=20)),
                ('date', models.DateField(validators=[core.models.present_or_future_date])),
                ('time', models.CharField(choices=[('Breakfast', 'Breakfast-Rs.30'), ('Lunch', 'Lunch-Rs.50'), ('Dinner', 'Dinner-Rs.60')], max_length=50)),
                ('expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
