# Generated by Django 4.1.5 on 2023-01-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(default=0, max_length=10)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='hostel',
            field=models.CharField(choices=[('Satluj East', 'Satluj East'), ('Satluj West', 'Satluj West'), ('Beas East', 'Beas East'), ('Beas West', 'Beas West'), ('Chenab East', 'Chenab East'), ('Chenab West', 'Chenab West'), ('Raavi East', 'Raavi East'), ('Raavi West', 'Raavi West')], max_length=100),
        ),
    ]
