# Generated by Django 4.1.5 on 2023-01-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otpmodel_alter_usermodel_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
