# Generated by Django 4.1.5 on 2023-01-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_otpmodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
