# Generated by Django 4.1.5 on 2023-01-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_otpmodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
