# Generated by Django 4.1.5 on 2023-01-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_otpmodel_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponmodel',
            name='expired',
        ),
    ]
