# Generated by Django 4.1.5 on 2023-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_couponmodel_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
