# Generated by Django 4.1.5 on 2023-01-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_couponmodel_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponmodel',
            options={'ordering': ('expired', 'date')},
        ),
    ]
